project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "Payton Miloser"
  navbar:
    background: "#6495ED"
    foreground: "#F2EBE2"
    right:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources+
  page-navigation: true
  back-to-top-navigation: true
  
  page-footer:  
    left: >-
     &#169; 2025 Payton Miloser &#8729; Made with [Quarto](https://quarto.org)
    right: 
      - text: "Contact"
        href: mailto:miloserp@iastate.edu

format:
  html:
    theme: assets/custom_light.scss
      # - cosmo
      # - assets/styles.scss
    css: styles.css
    toc: true
    highlight-style: assets/rainbowr-light.theme

resources: pdfjs