---
title: "Research"
format: html
html:
  toc: true
---

My research centers on developing and applying statistical methods to better understand complex ecological and environmental systems. I am especially interested in geospatial data analysis, non-parametric methods, and Bayesian modeling, which provide powerful tools for capturing spatial structure and uncertainty in ecological processes. My work often engages with real-world data from environmental and agricultural contexts, where flexible modeling and thoughtful inference are essential. 

I am currently working with [Dr. Jarad Niemi](https://raw.githubusercontent.com/jarad/cv/master/JaradNiemi-CV.pdf) for my Ph.D.

## Talks

1. **Conference on Applied Statistics in Agriculture and Natural Resources, *2025***

*Measuring Spatial Consistency in Simulated Crop Yield with Tensor-Product Splines and Interclass Correlation*

Payton Miloser$^{1}$, [Philip Dixon](https://www.stat.iastate.edu/people/philip-dixon/cv.pdf)^2^

::: award-callout
🏆 </strong>Award:</strong> 1st Place in Graduate Student Oral Competition
:::

<iframe width="560" height="315" src="https://www.youtube.com/embed/HGPGxJ42V7c?si=iujp6-OZuhepKOpY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>

</iframe>

```{=html}
<style>
.award-callout {
  background-color: #fff8dc;       /* Light warm background */
  border-left: 4px solid #f4c542; /* Bold colored bar on the left */
  padding: 0.25em 0.5em;
  margin: 0.2em 0;
  font-weight: 400;
  font-size: 0.85em;
  color: #6b4a00;
  border-radius: 4px;
  max-width: 500px;
  box-shadow: 1px 1px 5px rgba(0,0,0,0.1);
}
</style>
```

2. **Electronic Undergraduate Statistics Research Conference (eUSR), *2021***

*Bio-Surveillance of COVID-19 Data using Statistical Process Control,*

Payton Miloser^1^ , [Paul Stephenson](https://www.linkedin.com/in/paul-stephenson-393b73b5)^2^

::: award-callout
🏆 </strong>Award:</strong> 1st Place in Student Oral Competition

<https://www.causeweb.org/usproc/eusr/video-competition>
:::

<iframe width="560" height="315" src="https://www.youtube.com/embed/-Dsp_Hd9rhI?si=YrvVCduqB3hAXxaC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>

</iframe>


3. Miloser, P., Layman, N., & Roberts, A., Student Scholars Day (SSD), “Prime Labeling of
Friendship Graphs”, Grand Valley State University, Allendale, Michigan, USA. (April 10,
2019).

## Papers & Manuscripts

***[Masters Thesis](https://dr.lib.iastate.edu/handle/20.500.12876/105897):***  “Assessing Spatial Consistency using Spatio-Temporal Interactions with Generalized Additive Models”. Miloser $^1$, Dixon $^2$. June 2024.

***[McNair Thesis](https://scholarworks.gvsu.edu/mcnair_manuscripts/11/):***  “Bio-Surveillance of Covid-19 Data using Statistical Process Control”. Miloser $^1$, Stephenson $^2$. 2022.

## Posters & Collaborations
1. Emily Lopez, Jaanve Mehta, [Karin Dorman Ph.D.](https://www.bcb.iastate.edu/people/karin-dorman/cv.pdf), Ethan Bush, Payton Miloser. “Assessing
uniformity of coverage in PCR-amplified nanopore sequencing to diagnose avian infectious
bronchitis virus in chickens”. Iowa State University, Ames, Iowa, USA. (August 3, 2023)

2. Hazer Becic, Lavion Sumerlin, [Emily Berg Ph.D.](https://www.stat.iastate.edu/people/emily-berg/cv.pdf), Zirou Zhou, Payton Miloser. “Small Area
Estimation for Poverty Rate Indicators”. Iowa State University, Ames, Iowa, USA. (August 3,
2023).

3. Cathryn Barbour, Blanca Parker, [Heike Hoffman Ph.D.](https://heike.github.io/), [Alicia Carriquiry Ph.D.](https://www.stat.iastate.edu/people/alicia-carriquiry/cv.pdf), Payton
Miloser. “Estimating Probability of True Hits”. Iowa State University, Ames, Iowa, USA.
(August 3, 2023).

4. Miloser, P. McNair Scholars Program. “Bio-Surveillance of Covid-19 Data using Statistical
Process Control”, Grand Valley State University, Allendale, Michigan, USA. (July 16, 2021).
## 
